# Generated by Django 4.2.4 on 2023-09-02 15:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="athor",
            new_name="author",
        ),
    ]
